### ISSUE TITLE
Add version and url to user agent api request

### ISSUE THREAD

**Issue by killer0071234** [killer0071234/python-zamg#106]
**Is your feature request related to a problem? Please describe.**
        It is probably also helpful to have more meaningful information about the plugin/user-agent. Please include an URL (e.g. this github repo) and the version number of this integration. (Other best practices regarding user agents: https://developers.whatismybrowser.com/learn/browser-detection/user-agents/user-agent-best-practices) This can help with analyzing such situations.

**Describe the solution you'd like**
The header has now as user agent `python-zamg`. It shall also include the api version and url. Prefered url is this repo.

**Describe alternatives you've considered**
-

**Additional context**
_Originally posted by @Langdi in https://github.com/killer0071234/python-zamg/issues/104#issuecomment-1357327850_

**Comment by killer0071234** [comment]
@Langdi according to your request for a more meaningful `User-Agent`:

Example: `Python/3.9 +https://github.com/killer0071234/python-zamg python-zamg/0.2.2`

1. Python + Version of Python
2. Url to github repository
3. "Browser" and version of this integration

Are you ok with that?

**Comment by Langdi** [comment]
Sure, looks good to me.

**Comment by killer0071234** [comment]
Integrated into 0.2.2
