### ISSUE TITLE
Upcoming domain change to geosphere.at

### ISSUE THREAD

**Issue by dlang-geosphereat** [killer0071234/python-zamg#184]
Hi @killer0071234 !

Since January 2023 the organizations ZAMG and GBA merged to Geosphere Austria. As a result, the API provided currently under https://dataset.api.hub.zamg.ac.at/v1 will move to a new domain => https://dataset.api.hub.geosphere.at/v1 (not yet public)

This change also comes with infrastructure changes behind the scenes (which will lead to better performance in the future!). In order to not maintain multiple environments we are considering HTTP 301 redirects. However, this would break your package, as you are not following redirects: https://github.com/killer0071234/python-zamg/blob/main/src/zamg/zamg.py#L80
 
## Estimated timeline
The new domain will be public and the new canonical URL this summer, ideally July.

## Changes
For users only the domain will change. Any other changes in the future will be announced ahead of time to allow adjustments.

## Solution
Is there a specific reason why you don't follow redirects? This would be an easy solution for the upcoming change, that doesn't need a lot of coordination.

**Comment by killer0071234** [comment]
Hi @dlang-geosphereat!

Many thanks for your information about the ongoing progress of updating the data hub api.

There is no specific reason for a disallowed redirect. 

In a first step it will be the best if we allow redirects that there are no failed updates to the new url after the update on your side.

Later on we should change it to the new url.

BR

**Comment by dlang-geosphereat** [comment]
Thanks for your quick response.

 I agree that this is a good first step, as it gives both sides flexibility during this transition. We are still discussing how to move each service (there are other components we need to move), but having this option would obviously help a lot.

**Comment by dlang-geosphereat** [comment]
@killer0071234 Just a heads up, we already did change our domain. We also have a new Github Repository (https://github.com/Geosphere-Austria/dataset-api-docs) where you can track (upcoming) changes and give feedback.

**Comment by killer0071234** [comment]
> @killer0071234 Just a heads up, we already did change our domain. We also have a new Github Repository (https://github.com/Geosphere-Austria/dataset-api-docs) where you can track (upcoming) changes and give feedback.

Thanks for the information!
