### ISSUE TITLE
Using the new Zamg Datahub Api?

### ISSUE THREAD

**Issue by LuisThe0ne** [killer0071234/python-zamg#31]
**Is your feature request related to a problem? Please describe.**
The problem is, that with the current Api (OGD) there are only a few stations availible.

**Describe the solution you'd like**
Using the new Api provided by Zamg, would support all stations. ([Doku](https://dataset.api.hub.zamg.ac.at/v1/docs/?anonymous=true), [Example](https://github.com/LuisThe0ne/zamg-api-cli-client))

**Describe alternatives you've considered**
I think there is no alternative solution.?

**Additional context**
Example Request:
`https://dataset.api.hub.zamg.ac.at/v1/station/current/tawes-v1-10min?parameters=TL,P,FFAM&station_ids=11035`
to request Temperature, Pressure and Windspeed.

**Comment by killer0071234** [comment]
Hi,
Thanks for the hint to the new API!
You are right would be a very good improvement to have all stations available in HA.
I will have a look on it.

my base intention was just to update the zamg integration in HA, to have unique ids on the sensors to change icons, names etc. in the GUI.
but the effort to do this got a little bit out of control..

BR

**Comment by killer0071234** [comment]
Hi @LuisThe0ne,

The hint to use the new datahub API was pretty good ;-)
i had moved over the zamg client to the datahub API.

Thanks!

**Comment by ldoench** [comment]
Thank you very much for implementing the new data API! 
Do you have any plans to also have a look at the forecast API, if they gonna release it Q1 2023 ?

**Comment by killer0071234** [comment]
> Thank you very much for implementing the new data API!

No Problem!

> Do you have any plans to also have a look at the forecast API, if they gonna release it Q1 2023 ?

Currently not, but if it's released we will see ;-)

**Comment by ldoench** [comment]
Now there is some publication for upcoming weather information, but they only distribute it through ftp and as a package for the whole region (45.5 - 49.48 °N, 8.1 - 17.74 °E) in a 1*1km grid.

Here is the link: https://data.hub.zamg.ac.at/dataset/inca_fcst-v1-15min-1km
